apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-webapp
  labels:
    app: python-webapp
  namespace: namespace-workflow-1688399390169
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-webapp
  template:
    metadata:
      labels:
        app: python-webapp
    spec:
      containers:
        - name: python-webapp
          image: acrworkflow1688395556455.azurecr.io/image-workflow-1688399390169:latest
          ports:
            - containerPort: 8080