apiVersion: v1
kind: Service
metadata:
  name: SampleWorkflow1
  namespace: namespace-workflow-1688395556455
spec:
  type: LoadBalancer
  selector:
    app: SampleWorkflow1
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000