apiVersion: v1
kind: Service
metadata:
  name: python-webapp
  namespace: namespace-workflow-1688399390169
spec:
  type: LoadBalancer
  selector:
    app: python-webapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080